services:
  php:
    container_name: php-fpm-container
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./www/html/:/var/www/html/

  web:
    container_name: nginx-container
    build: 
      context: ./nginx
    ports:
      - '8080:80'
    volumes:
      - ./www/html/:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php