services:
  web:
    build: ./nginx/
    container_name: nginx-container
    ports:
      - 8080:80
    volumes:
      - ./www/html/:/var/www/html/
    links:
      - php

  php:
    build: ./php/
    container_name: php-fpm-container
    expose:
      - 9000
    volumes:
      - ./www/html/:/var/www/html/