services:
  db:
    container_name: mariadb
    image: mariadb:10.7.1
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mariadb:/app/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gildedrose
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
  
  php:
    container_name: php-fpm
    build:
      context: ./docker/php
    volumes:
      - ./app:/app
    working_dir: "/app"
    depends_on:
      - db

  web:
    container_name: nginx
    image: nginx:1.21.4
    restart: on-failure
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf 
    ports:
      - "8080:80"
    depends_on:
      - db
      - php
