parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    App\Updater\BackstageUpdater: ~
    App\Updater\BrieUpdater: ~
    App\Updater\ConjuredUpdater: ~
    App\Updater\SulfurasUpdater: ~
    App\StockManager:
        arguments:
            $updaters:
                - '@App\Updater\BackstageUpdater'
                - '@App\Updater\BrieUpdater'
                - '@App\Updater\ConjuredUpdater'
                - '@App\Updater\SulfurasUpdater'
    App\Updater\DefaultUpdater: ~
    App\Updater\UpdaterInterface: '@App\Updater\DefaultUpdater'