parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Command\FixturePrinterCommand:
        tags:
            - { name: 'console.command', command: 'app:fixtures:print' }

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    App\Repository\:
        resource: '../src/Repository'
        tags: ['doctrine.repository_service']

    App\DataFixtures\:
        resource: '../src/DataFixtures'
        tags: ['doctrine.fixture.orm']

    App\Updater\BackstageUpdater: ~
    App\Updater\BrieUpdater: ~
    App\Updater\ConjuredUpdater: ~
    App\Updater\SulfurasUpdater: ~
    App\Updater\UpdaterManager:
        arguments:
            $updaters:
                - '@App\Updater\BackstageUpdater'
                - '@App\Updater\BrieUpdater'
                - '@App\Updater\ConjuredUpdater'
                - '@App\Updater\SulfurasUpdater'
    App\Updater\DefaultUpdater: ~
    App\Updater\UpdaterInterface: '@App\Updater\DefaultUpdater'
