parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
<<<<<<< Updated upstream
    App\:
=======

    GildedRose\:
>>>>>>> Stashed changes
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
<<<<<<< Updated upstream
    App\Updater\BackstageUpdater: ~
    App\Updater\BrieUpdater: ~
    App\Updater\ConjuredUpdater: ~
    App\Updater\SulfurasUpdater: ~
    App\StockManager:
        arguments:
            $updaters:
                - '@App\Updater\BackstageUpdater'
                - '@App\Updater\BrieUpdater'
                - '@App\Updater\ConjuredUpdater'
                - '@App\Updater\SulfurasUpdater'
    App\Updater\DefaultUpdater: ~
    App\Updater\UpdaterInterface: '@App\Updater\DefaultUpdater'
=======

    GildedRose\Updater\BackstageUpdater: ~
    GildedRose\Updater\BrieUpdater: ~
    GildedRose\Updater\ConjuredUpdater: ~
    GildedRose\Updater\SulfurasUpdater: ~
    GildedRose\StockManager:
        arguments:
            $updaters:
                - '@GildedRose\Updater\BackstageUpdater'
                - '@GildedRose\Updater\BrieUpdater'
                - '@GildedRose\Updater\ConjuredUpdater'
                - '@GildedRose\Updater\SulfurasUpdater'

    GildedRose\Updater\DefaultUpdater: ~
    GildedRose\Updater\UpdaterInterface: '@GildedRose\Updater\DefaultUpdater'
>>>>>>> Stashed changes
