#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use GildedRose\Data\FileContentRetriever;
use GildedRose\Command\TestFixtureCommand;
use GildedRose\Printer\StockPrinter;
use GildedRose\Repository\ItemRepository;
use GildedRose\Serializer\ItemNormalizer;
use GildedRose\Serializer\ItemsNormalizer;
use GildedRose\StockManager;
use GildedRose\Updater;
use GildedRose\Validator\Checker\DefaultChecker;
use GildedRose\Validator\Checker\SulfurasChecker;
use Symfony\Component\Console\Application;
use Symfony\Component\Serializer\Encoder\CsvEncoder;

$application = new Application('Gilded Rose CLI', '0.1.1');

$commands = [
    new TestFixtureCommand(
        new ItemRepository(
            new FileContentRetriever(),
            new CsvEncoder(), 
            new ItemsNormalizer(new ItemNormalizer())
        ),
        new StockManager(
            new Updater\DefaultUpdater(),
            [
                new Updater\BackstageUpdater(),
                new Updater\BrieUpdater(),
                new Updater\ConjuredUpdater(),
                new Updater\SulfurasUpdater()
            ],
            new DefaultChecker(),
            [
                new SulfurasChecker()
            ]
        ),
        new StockPrinter()
    )
];

foreach ($commands as $command) {
    $application->add($command);
}

$application->run();
