#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use GildedRose\Command\TestFixtureCommand;
use GildedRose\Repository\ItemRepository;
use GildedRose\Serializer\ItemNormalizer;
use GildedRose\Serializer\ItemsNormalizer;

use Symfony\Component\Console\Application;
use Symfony\Component\Serializer\Encoder\CsvEncoder;

$application = new Application('Gilded Rose CLI', '0.1.1');

$fileInfo = new SplFileInfo(__DIR__ . '/data/testfixture.csv');

$filePath = $fileInfo->getRealPath();

$commands = [
    new TestFixtureCommand(
        new ItemRepository(
            new CsvEncoder, 
            new ItemsNormalizer(new ItemNormalizer),
            $filePath
        )
    )
    // register new commands here
    ];

for ($i = 0; $i < count($commands); $i++) {
    $application->add($commands[$i]);
}

$application->run();
